// labs/lab3/src/views/Register.vue
<template>
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-4">
        <div class="card shadow auth-card">
          <div class="card-body p-4">
            <div class="auth-header">
              <h3 class="card-title text-center mb-2">Регистрация</h3>
              <p class="text-muted text-center">Создайте новый аккаунт</p>
            </div>

            <form @submit.prevent="onSubmit" :class="{ 'was-validated': validated }" novalidate>
              <div class="mb-3">
                <label class="form-label">Имя пользователя</label>
                <input
                    v-model="username"
                    type="text"
                    class="form-control"
                    required
                    minlength="3"
                    autocomplete="username"
                />
                <div class="invalid-feedback">Минимум 3 символа</div>
              </div>

              <div class="mb-3">
                <label class="form-label">Email</label>
                <input
                    v-model="email"
                    type="email"
                    class="form-control"
                    required
                    autocomplete="email"
                />
                <div class="invalid-feedback">Введите корректный email</div>
              </div>

              <div class="mb-3">
                <label class="form-label">Пароль</label>
                <input
                    v-model="password"
                    type="password"
                    class="form-control"
                    required
                    minlength="6"
                    autocomplete="new-password"
                />
                <div class="invalid-feedback">Пароль должен быть минимум 6 символов</div>
              </div>

              <button class="btn btn-primary w-100 mb-3" :disabled="loading">
                {{ loading ? 'Создание...' : 'Зарегистрироваться' }}
              </button>

              <div class="text-center">
                <span>Уже есть аккаунт?</span>
                <RouterLink to="/login" class="text-decoration-none">Войти</RouterLink>
              </div>
            </form>

            <div v-if="message" :class="['alert', messageType, 'mt-3']">
              {{ message }}
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { register } from '@/api/auth.api';
import { useRouter } from 'vue-router';

const username = ref('');
const email = ref('');
const password = ref('');
const loading = ref(false);
const validated = ref(false);

const message = ref('');
const messageType = ref('');

const router = useRouter();

async function onSubmit() {
  validated.value = true;

  if (!username.value || username.value.length < 3) return;
  if (!email.value) return;
  if (!password.value || password.value.length < 6) return;

  loading.value = true;
  message.value = '';

  try {
    await register(email.value, password.value, username.value);

    message.value = 'Аккаунт успешно создан';
    messageType.value = 'alert-success';

    setTimeout(() => {
      router.push('/profile');
    }, 500);
  } catch (err) {
    message.value = err.message || 'Ошибка регистрации';
    messageType.value = 'alert-danger';
  }

  loading.value = false;
}
</script>

<style scoped>
.auth-card {
  border-radius: 12px;
}
</style>

// labs/K3440/Khurs_Pavel/LR3/app/register/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { UserPlus } from 'lucide-react';

export default function RegisterPage() {
  const router = useRouter();
  const { register } = useAuth();
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (password !== confirmPassword) {
      setError('Пароли не совпадают');
      return;
    }

    if (password.length < 6) {
      setError('Пароль должен быть не менее 6 символов');
      return;
    }

    setIsLoading(true);

    try {
      await register(email, password, name, phone);
      router.push('/properties');
    } catch (err) {
      setError('Ошибка при регистрации. Возможно, пользователь с таким email уже существует');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="container flex items-center justify-center min-h-[calc(100vh-200px)] py-8">
      <Card className="w-full max-w-md">
        <CardHeader className="space-y-1">
          <CardTitle className="text-2xl font-bold flex items-center gap-2">
            <UserPlus className="h-6 w-6" />
            Регистрация
          </CardTitle>
          <CardDescription>
            Создайте аккаунт для доступа ко всем функциям
          </CardDescription>
        </CardHeader>
        <form onSubmit={handleSubmit}>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="name">Имя</Label>
              <Input
                id="name"
                type="text"
                placeholder="Иван Иванов"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="ivan@example.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="phone">Телефон</Label>
              <Input
                id="phone"
                type="tel"
                placeholder="+7 (999) 123-45-67"
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Пароль</Label>
              <Input
                id="password"
                type="password"
                placeholder="Минимум 6 символов"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="confirmPassword">Подтверждение пароля</Label>
              <Input
                id="confirmPassword"
                type="password"
                placeholder="Повторите пароль"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                required
              />
            </div>
            {error && (
              <p className="text-sm text-destructive">{error}</p>
            )}
          </CardContent>
          <CardFooter className="flex flex-col gap-4">
            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? 'Регистрация...' : 'Зарегистрироваться'}
            </Button>
            <p className="text-sm text-center text-muted-foreground">
              Уже есть аккаунт?{' '}
              <Link href="/login" className="text-primary hover:underline">
                Войти
              </Link>
            </p>
          </CardFooter>
        </form>
      </Card>
    </div>
  );
}
