// labs/K3440/Оспельников Алексей/lr3/rent/src/views/Register.vue
<template>
  <div>
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <div class="card shadow-sm">
            <div class="card-body">
              <h3 class="card-title mb-4">Регистрация</h3>
              <form @submit.prevent="handleRegister">
                <div class="mb-3">
                  <label class="form-label">Полное имя</label>
                  <input v-model="fullname" type="text" class="form-control" required>
                </div>
                <div class="mb-3">
                  <label class="form-label">Email</label>
                  <input v-model="email" type="email" class="form-control" required>
                </div>
                <div class="mb-3">
                  <label class="form-label">Телефон</label>
                  <input v-model="phone" type="tel" class="form-control" required>
                </div>
                <div class="mb-3">
                  <label class="form-label">Город</label>
                  <select v-model="city" class="form-select" required>
                    <option disabled value="">Выберите город</option>
                    <option>Москва</option>
                    <option>Санкт-Петербург</option>
                    <option>Екатеринбург</option>
                    <option>Новосибирск</option>
                  </select>
                </div>
                <div class="mb-3">
                  <label class="form-label">Пароль</label>
                  <input v-model="password" type="password" class="form-control" required>
                </div>
                <div class="mb-3">
                  <label class="form-label">Подтвердите пароль</label>
                  <input v-model="confirmPassword" type="password" class="form-control" required>
                </div>
                <div class="mb-3 form-check">
                  <input v-model="agree" type="checkbox" class="form-check-input" required>
                  <label class="form-check-label">
                    Я согласен с <a href="#">правилами сервиса</a>
                  </label>
                </div>
                <div class="mb-3 form-check">
                  <input v-model="remember" type="checkbox" class="form-check-input">
                  <label class="form-check-label">Запомнить меня</label>
                </div>
                <button type="submit" class="btn btn-primary w-100">Зарегистрироваться</button>
              </form>
              <hr>
              <div class="text-center">
                Уже есть аккаунт? <router-link to="/login">Войти</router-link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Navbar from '../components/Navbar.vue';
import Footer from '../components/Footer.vue';
import axios from 'axios';
import { useAuth } from '../composables/useAuth';

export default {
  components: { Navbar, Footer },
  data() {
    return {
      fullname: '',
      email: '',
      phone: '',
      city: '',
      password: '',
      confirmPassword: '',
      agree: false,
      remember: false
    };
  },
  setup() {
    const auth = useAuth();
    return { auth };
  },
  methods: {
    async handleRegister() {
      if (this.password !== this.confirmPassword) {
        alert('Пароли не совпадают');
        return;
      }
      try {
        const res = await axios.post('http://localhost:8000/auth/register', {
          email: this.email,
          fullname: this.fullname,
          phone: this.phone,
          city: this.city,
          password: this.password
        });

        // После регистрации сразу логиним пользователя
        const loginSuccess = await this.auth.login({
          email: this.email,
          password: this.password,
          remember: this.remember
        });

        if (loginSuccess) {
          alert('Регистрация и вход успешны!');
          this.$router.push('/');
        } else {
          alert('Ошибка при автоматическом входе');
        }

      } catch (err) {
        console.error(err);
        alert(err.response?.data?.message || 'Сетевая ошибка');
      }
    }
  }
};
</script>

// labs/K3440/Khurs_Pavel/LR3/app/register/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { UserPlus } from 'lucide-react';

export default function RegisterPage() {
  const router = useRouter();
  const { register } = useAuth();
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (password !== confirmPassword) {
      setError('Пароли не совпадают');
      return;
    }

    if (password.length < 6) {
      setError('Пароль должен быть не менее 6 символов');
      return;
    }

    setIsLoading(true);

    try {
      await register(email, password, name, phone);
      router.push('/properties');
    } catch (err) {
      setError('Ошибка при регистрации. Возможно, пользователь с таким email уже существует');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="container flex items-center justify-center min-h-[calc(100vh-200px)] py-8">
      <Card className="w-full max-w-md">
        <CardHeader className="space-y-1">
          <CardTitle className="text-2xl font-bold flex items-center gap-2">
            <UserPlus className="h-6 w-6" />
            Регистрация
          </CardTitle>
          <CardDescription>
            Создайте аккаунт для доступа ко всем функциям
          </CardDescription>
        </CardHeader>
        <form onSubmit={handleSubmit}>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="name">Имя</Label>
              <Input
                id="name"
                type="text"
                placeholder="Иван Иванов"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="ivan@example.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="phone">Телефон</Label>
              <Input
                id="phone"
                type="tel"
                placeholder="+7 (999) 123-45-67"
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Пароль</Label>
              <Input
                id="password"
                type="password"
                placeholder="Минимум 6 символов"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="confirmPassword">Подтверждение пароля</Label>
              <Input
                id="confirmPassword"
                type="password"
                placeholder="Повторите пароль"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                required
              />
            </div>
            {error && (
              <p className="text-sm text-destructive">{error}</p>
            )}
          </CardContent>
          <CardFooter className="flex flex-col gap-4">
            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? 'Регистрация...' : 'Зарегистрироваться'}
            </Button>
            <p className="text-sm text-center text-muted-foreground">
              Уже есть аккаунт?{' '}
              <Link href="/login" className="text-primary hover:underline">
                Войти
              </Link>
            </p>
          </CardFooter>
        </form>
      </Card>
    </div>
  );
}
