// labs/K3440/Khurs_Pavel/LR3/components/layout/ThemeToggle.tsx
'use client';

import { Moon, Sun } from 'lucide-react';
import { useTheme } from '@/contexts/ThemeContext';
import { Button } from '@/components/ui/button';

export function ThemeToggle() {
  const { theme, toggleTheme } = useTheme();

  return (
    <Button
      variant="ghost"
      size="icon"
      onClick={toggleTheme}
      aria-label="Toggle theme"
    >
      {theme === 'light' ? (
        <Moon className="h-5 w-5" />
      ) : (
        <Sun className="h-5 w-5" />
      )}
    </Button>
  );
}

// labs/Петухов Семён 2.2/Lab3/src/components/ThemeToggle.vue
<template>
  <button
    id="themeToggle"
    class="btn btn-sm btn-outline-secondary theme-toggle btn-icon"
    type="button"
    :aria-pressed="isDark"
    :aria-label="toggleLabel"
    :title="toggleLabel"
    @click="toggleTheme"
  >
    <svg class="icon theme-toggle-icon" aria-hidden="true" focusable="false">
      <use v-if="!isDark" href="#icon-moon"></use>
      <use v-else href="#icon-sun"></use>
    </svg>
    <span class="visually-hidden">{{ toggleLabel }}</span>
  </button>
</template>

<script setup>
import { computed } from 'vue'
import { useTheme } from '@/composables/useTheme'

const { currentTheme, toggleTheme: toggle } = useTheme()

const isDark = computed(() => currentTheme.value === 'dark')
const toggleLabel = computed(() => isDark.value ? 'Включить светлую тему' : 'Включить тёмную тему')

function toggleTheme() {
  toggle()
}
</script>
