// labs/K3440/Khurs_Pavel/LR3/components/layout/ThemeToggle.tsx
'use client';

import { Moon, Sun } from 'lucide-react';
import { useTheme } from '@/contexts/ThemeContext';
import { Button } from '@/components/ui/button';

export function ThemeToggle() {
  const { theme, toggleTheme } = useTheme();

  return (
    <Button
      variant="ghost"
      size="icon"
      onClick={toggleTheme}
      aria-label="Toggle theme"
    >
      {theme === 'light' ? (
        <Moon className="h-5 w-5" />
      ) : (
        <Sun className="h-5 w-5" />
      )}
    </Button>
  );
}

// labs/K3441/Красюк Карина/lab3/src/components/ThemeToggle.vue
<template>
  <button
    class="btn btn-outline-light btn-sm theme-toggle"
    @click="toggleTheme"
    :aria-label="currentTheme === 'dark' ? 'Переключить на светлую тему' : 'Переключить на тёмную тему'"
  >
    <span class="icon icon-sm">
      <svg><use :href="currentTheme === 'dark' ? '#icon-sun' : '#icon-moon'"></use></svg>
    </span>
  </button>
</template>

<script setup>
import { computed } from 'vue'
import { useTheme } from '@/composables/useTheme'

const { currentTheme, toggleTheme } = useTheme()
</script>
