// labs/K3440/Khurs_Pavel/LR3/app/login/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { LogIn } from 'lucide-react';

export default function LoginPage() {
  const router = useRouter();
  const { login } = useAuth();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      await login(email, password);
      router.push('/properties');
    } catch (err) {
      setError('Неверный email или пароль');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="container flex items-center justify-center min-h-[calc(100vh-200px)] py-8">
      <Card className="w-full max-w-md">
        <CardHeader className="space-y-1">
          <CardTitle className="text-2xl font-bold flex items-center gap-2">
            <LogIn className="h-6 w-6" />
            Вход
          </CardTitle>
          <CardDescription>
            Введите email и пароль для входа в систему
          </CardDescription>
        </CardHeader>
        <form onSubmit={handleSubmit}>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="test@test.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Пароль</Label>
              <Input
                id="password"
                type="password"
                placeholder="••••••••"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </div>
            {error && (
              <p className="text-sm text-destructive">{error}</p>
            )}
            <p className="text-sm text-muted-foreground">
              Тестовые данные: test@test.com / password123
            </p>
          </CardContent>
          <CardFooter className="flex flex-col gap-4">
            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? 'Вход...' : 'Войти'}
            </Button>
            <p className="text-sm text-center text-muted-foreground">
              Нет аккаунта?{' '}
              <Link href="/register" className="text-primary hover:underline">
                Зарегистрироваться
              </Link>
            </p>
          </CardFooter>
        </form>
      </Card>
    </div>
  );
}

// labs/K3441/Кадникова Екатерина/lab3/src/views/Login.vue
<template>
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-4">
        <div class="card shadow auth-card">
          <div class="card-body p-4">
            <div class="auth-header">
              <h3 class="card-title text-center mb-2">Вход в аккаунт</h3>
              <p class="text-muted text-center">Введите ваши учетные данные</p>
            </div>

            <form @submit.prevent="onSubmit" novalidate :class="{ 'was-validated': validated }">
              <div class="mb-3">
                <label class="form-label">Email</label>
                <input
                    v-model="email"
                    type="email"
                    class="form-control"
                    required
                    autocomplete="email"
                />
                <div class="invalid-feedback">Введите корректный email</div>
              </div>

              <div class="mb-3">
                <label class="form-label">Пароль</label>
                <input
                    v-model="password"
                    type="password"
                    class="form-control"
                    required
                    minlength="6"
                    autocomplete="current-password"
                />
                <div class="invalid-feedback">Пароль должен содержать минимум 6 символов</div>
              </div>

              <button class="btn btn-primary w-100 mb-3" :disabled="loading">
                {{ loading ? 'Вход...' : 'Войти' }}
              </button>

              <div class="text-center">
                <span>Нет аккаунта? </span>
                <RouterLink to="/register" class="text-decoration-none">
                  Зарегистрироваться
                </RouterLink>
              </div>
            </form>

            <div v-if="message" :class="['alert', messageType, 'mt-3']">
              {{ message }}
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { login } from '@/api/auth.api';
import { useRouter } from 'vue-router';

const email = ref('');
const password = ref('');
const loading = ref(false);
const validated = ref(false);

const message = ref('');
const messageType = ref('');

const router = useRouter();

async function onSubmit() {
  validated.value = true;

  if (!email.value || !password.value || password.value.length < 6) {
    return;
  }

  loading.value = true;
  message.value = '';

  try {
    await login(email.value, password.value);
    message.value = 'Вход выполнен успешно';
    messageType.value = 'alert-success';

    setTimeout(() => {
      router.push('/profile');
    }, 500);
  } catch (err) {
    message.value = err.message || 'Ошибка входа';
    messageType.value = 'alert-danger';
  }

  loading.value = false;
}
</script>

<style scoped>
.auth-card {
  border-radius: 12px;
}
</style>
