// labs/К3343/Зарецкий Юрий/lab1/src/components/common/ThemeToggle.vue
<template>
  <button
    type="button"
    class="btn btn-outline-light theme-toggle-btn d-inline-flex align-items-center"
    :aria-pressed="isDark"
    @click="toggleTheme"
  >
    <Icon 
      :name="isDark ? 'sun' : 'moon'" 
      size="md" 
      extra-class="me-2 icon-inline"
    />
    <span>{{ isDark ? 'Светлая тема' : 'Тёмная тема' }}</span>
  </button>
</template>

<script setup>
import { computed } from 'vue'
import { useTheme } from '@/composables/useTheme'
import Icon from './Icon.vue'

const { theme, isDark, toggleTheme } = useTheme()
</script>

// labs/K3440/Khurs_Pavel/LR3/components/layout/ThemeToggle.tsx
'use client';

import { Moon, Sun } from 'lucide-react';
import { useTheme } from '@/contexts/ThemeContext';
import { Button } from '@/components/ui/button';

export function ThemeToggle() {
  const { theme, toggleTheme } = useTheme();

  return (
    <Button
      variant="ghost"
      size="icon"
      onClick={toggleTheme}
      aria-label="Toggle theme"
    >
      {theme === 'light' ? (
        <Moon className="h-5 w-5" />
      ) : (
        <Sun className="h-5 w-5" />
      )}
    </Button>
  );
}
